# Generated by Django 6.0.6 on 2026-08-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='brach',
            new_name='branch',
        ),
    ]
