# Generated by Django 6.0.6 on 2026-08-12 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_rename_brach_theme_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myweb.field')),
            ],
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
