# Generated by Django 6.0.6 on 2026-08-12 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_branch_delete_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
                ('dp', models.TextField()),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myweb.branch')),
            ],
        ),
    ]
