# Generated by Django 6.0.6 on 2026-08-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='video',
        ),
    ]
